<html>
	<head>
		<title>Gerar QRcode com PHP</title>
		
		<style type="text/css">
		<!--
		body { background-color:#FFFFFF;  }
		h1 { color:#000000; font-family:Arial,Helvetica,Geneva; font-size:12pt; }
		p,li { color:#000080; font-family:Arial,Helvetica,Geneva; font-size:10pt; }
		-->
</style>
<style type="text/css">
.classname {
    -moz-box-shadow:inset 0px 1px 0px 0px #caefab;
    -webkit-box-shadow:inset 0px 1px 0px 0px #caefab;
    box-shadow:inset 0px 1px 0px 0px #caefab;
    background-color:#77d42a;
    -moz-border-radius:6px;
    -webkit-border-radius:6px;
    border-radius:6px;
    border:1px solid #268a16;
    display:inline-block;
    color:#306108;
    font-family:arial;
    font-size:15px;
    font-weight:bold;
    padding:6px 24px;
    text-decoration:none;
    text-shadow:1px 1px 0px #aade7c;
}.classname:hover {
    background-color:#5cb811;
}.classname:active {
    position:relative;
    top:1px;
}
/* This imageless css button was generated by CSSButtonGenerator.com */
</style>

	</head>
	<body>
		<h1>Gerar QRcode com PHP</h1>
		<br>
		<form action="php/img.php" method="POST">
		<input type="text" name="campo" id="campo" style="border-radius:3px; border:1px #008080 solid; width:600px; height:30px; color:#C0C0C0; text-align:center; ">
		<button class="classname">Novo QRcode</button>
		</form>
		<?php
 $pasta = 'img_php/';

 $arquivos = glob("$pasta{*.jpg,*.png,*.gif,*.bmp}", GLOB_BRACE);
 foreach($arquivos as $img){?>
<img src="<?php echo $img; ?>" alt="<?php echo $img; ?>" title="<?php echo $img; ?>" width="150"/><br />
 <?php  
 }

?>

	</body>
</html>